package com.procurepal_services.stock_bridge_api.product.bulk;

import com.procurepal_services.stock_bridge_api.imports.io.ImportLimits;
import java.util.List;

/**
 * What the product template needs to know about the company it is for: whether it sells (the
 * selling price column), its supplier and category names (the two dropdowns), and whether codes
 * are generated for it (no code column).
 */
public record ProductTemplateContext(
        boolean isSeller, List<String> vendorNames, boolean skuAutoGenerated, List<String> categoryNames) {

    public ProductTemplateContext {
        vendorNames = vendorNames == null ? List.of() : List.copyOf(vendorNames);
        categoryNames = categoryNames == null ? List.of() : List.copyOf(categoryNames);
    }

    public ProductTemplateContext(boolean isSeller, List<String> vendorNames, boolean skuAutoGenerated) {
        this(isSeller, vendorNames, skuAutoGenerated, List.of());
    }

    public static ProductTemplateContext of(boolean isSeller) {
        return new ProductTemplateContext(isSeller, List.of(), false, List.of());
    }

    /** Past the cap a dropdown is no help - the list is left off and the cell is free text. */
    public List<String> vendorDropdownNames() {
        return vendorNames.size() > ImportLimits.VENDOR_DROPDOWN_CAP ? List.of() : vendorNames;
    }
}
