package com.procurepal_services.stock_bridge_api.product.bulk;

import com.procurepal_services.stock_bridge_api.entity.Product;
import com.procurepal_services.stock_bridge_api.imports.io.LookupSheetWriter;
import com.procurepal_services.stock_bridge_api.imports.io.NumberValues;
import com.procurepal_services.stock_bridge_api.imports.io.TemplateConventions;
import com.procurepal_services.stock_bridge_api.imports.io.WorkbookBuilder;
import com.procurepal_services.stock_bridge_api.product.unit.UnitOfMeasure;
import com.procurepal_services.stock_bridge_api.product.unit.PackContents;
import com.procurepal_services.stock_bridge_api.product.unit.UnitOption;
import com.procurepal_services.stock_bridge_api.product.unit.UnitOptions;
import java.math.BigDecimal;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.UUID;
import lombok.RequiredArgsConstructor;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.springframework.stereotype.Service;

/**
 * Writes the product sheet and the "Download my products" export (BULK_IMPORT_CX_PLAN.md tasks
 * 1.6 and 2.3). Reading an uploaded sheet is the import engine's job
 * ({@code ProductCatalogRowHandler}); this class only decides what the file looks like.
 *
 * <h2>One layout for both files</h2>
 * The template and the export share {@link #SHEET_FIELDS} and {@link #SHEET_HEADERS}, so an
 * exported sheet can be edited and uploaded back through the import page. The export adds a hidden
 * Ref column ({@link ProductRefs}), which is how each row finds its product again.
 *
 * <h2>What the reader sees</h2>
 * A help tab first; headers in plain words; a grey guidance row; a note and three worked examples
 * ({@link #EXAMPLE_ROWS}) that are dropped at upload only if left exactly as shipped
 * ({@link #isShippedExample}); dropdowns for what it comes in, the supplier and the category.
 *
 * <h2>Quantities and prices are written in the terms they are read in</h2>
 * "How many you have now" and "Warn me when I have" count packs when the row has one, and "Price
 * you pay for one" is per pack - so the export divides and multiplies what is stored (per stock
 * unit) accordingly ({@code inSheetUnits}, {@code inSheetPrice}). Writing the stored figure
 * instead would multiply the catalog by the pack size on every round trip.
 */
@Service
@RequiredArgsConstructor
public class ProductExcelService {

    /**
     * One short sentence per column, anchored on that column's own header - replacing the single
     * paragraph-long comment the previous template put on B1. See
     * {@code WorkbookBuilder.writeHeaderRow} for why that change matters more than it looks:
     * four rules in one cell is where nobody reads them.
     *
     * <p>{@code unit_price}'s text is tenant-conditional and is therefore composed in
     * {@link #headerCommentsFor}, not here.
     *
     * <h2>Rewritten as a set for UNIT_UX_CONTRACT.md section 9</h2>
     * These comments are the primary UI for most of this product's users - far more of them fill
     * the spreadsheet in than ever open the product form - so they are written as one set that
     * teaches one model, not as thirteen independently maintained sentences.
     *
     * <p>The three that carry the model are {@code opening_stock}, {@code low_stock_alert_at}
     * and {@code cost_price}. The first two say the number is in PACKS when the row has one
     * (section 9.1); the third says the money is NOT (section 9.2). That divergence is the one
     * thing a user can get wrong here, so both halves are stated in the concrete terms of the
     * example row sitting two rows below - kegs and millilitres - rather than in the abstract
     * "stock unit" the columns are named after. "Per ml, not per keg" is a sentence somebody can
     * check against their invoice; "per stock unit" is one they have to translate first.
     */
    public static final String EXAMPLE_SKU_MARKER_PREFIX = "EXAMPLE-SKU-DELETE-ME";

    /**
     * The same trick as {@link #EXAMPLE_SKU_MARKER_PREFIX}, carried on {@code name} instead of
     * {@code sku} - for the one template shape that has no {@code sku} column to carry it on: a
     * tenant with automatic SKU generation on (see {@code ProductSkuSettings}, {@link
     * ProductTemplateContext#skuAutoGenerated}). {@code name} is always present and always
     * required, so it is the only column guaranteed to exist to hang this on in that case.
     */
    public static final String EXAMPLE_NAME_MARKER_PREFIX = "EXAMPLE-DELETE-ME";

    /** Defined names on the hidden {@code _lookups} sheet - see {@link LookupSheetWriter}. */

    private static final String PACKAGING_UNITS_RANGE = "packaging_units";

    private static final String VENDOR_NAMES_RANGE = "vendor_names";

    private static final String CATEGORY_NAMES_RANGE = "category_names";

    // ------------------------------------------------------------------------------------------
    // The product sheet as people see it (BULK_IMPORT_CX_PLAN.md task 1.6). Columns are still
    // addressed by their import field key; SHEET_HEADERS is what the header cell says, and
    // ImportColumnMapper maps those words back onto the keys.
    // ------------------------------------------------------------------------------------------

    /** Template and export column order: what it is, how you buy it, what you have, the rest. */
    static final List<String> SHEET_FIELDS = List.of(
            "name", "sku", "pack", "contains", "vendor_name", "opening_stock", "cost_price", "unit_price",
            "low_stock_alert_at", "category", "description", "vendor_sku", "barcode");

    static final Map<String, String> SHEET_HEADERS = Map.ofEntries(
            Map.entry("name", "Product name *"),
            Map.entry("sku", "Your code *"),
            Map.entry("pack", "Comes in"),
            Map.entry("contains", "Size of one"),
            Map.entry("vendor_name", "Supplier"),
            Map.entry("opening_stock", "How many you have now"),
            Map.entry("cost_price", "Price you pay for one (\u20a6)"),
            Map.entry("unit_price", "Selling price (\u20a6) *"),
            Map.entry("low_stock_alert_at", "Warn me when I have"),
            Map.entry("category", "Category"),
            Map.entry("description", "Notes"),
            Map.entry("vendor_sku", "Supplier's code for it"),
            Map.entry("barcode", "Barcode"),
            Map.entry("ref", "Ref"));

    /**
     * "Download my products" (BULK_IMPORT_CX_PLAN.md task 2.3): the template's columns plus a hidden
     * Ref, which is how an edited sheet finds each product again when it is uploaded back.
     */
    static final List<String> EXPORT_FIELDS = java.util.stream.Stream
            .concat(SHEET_FIELDS.stream(), java.util.stream.Stream.of("ref"))
            .toList();

    private static final Map<String, String> SHEET_GUIDANCE = Map.ofEntries(
            Map.entry("name", "What your staff call it. e.g. Rice (Mama Gold)"),
            Map.entry("sku", "Your own code for it. Must be different for every product."),
            Map.entry("pack", "Bag, Carton, Keg... Pick from the list. Blank if you buy it loose."),
            Map.entry("contains", "What is inside ONE. 50 kg \u00b7 12 x 750 ml. Loose? Just the unit: kg"),
            Map.entry("vendor_name", "Who you buy it from. Pick one or type a new name. Optional."),
            Map.entry("opening_stock", "Optional. Counted in what \"Comes in\" says - 20 means 20 bags."),
            Map.entry("cost_price", "Optional. For ONE of \"Comes in\" - per bag, not per kg."),
            Map.entry("unit_price", "What you sell it for, per kg, litre or piece - not per bag."),
            Map.entry("low_stock_alert_at", "Optional. Counted the same way as \"How many you have now\"."),
            Map.entry("category", "Optional. Pick one or type a new one - we'll add it."),
            Map.entry("description", "Optional. Anything you want on the product page."),
            Map.entry("vendor_sku", "Optional. The supplier's own code, if they use one."),
            Map.entry("barcode", "Optional. The barcode on the box, so you can scan it later."),
            Map.entry("ref", "Leave alone - it's how we recognise the product."));

    private static final Map<String, Integer> SHEET_WIDTHS = Map.ofEntries(
            Map.entry("name", 30), Map.entry("sku", 16), Map.entry("pack", 14), Map.entry("contains", 18),
            Map.entry("vendor_name", 22), Map.entry("opening_stock", 16), Map.entry("cost_price", 18),
            Map.entry("unit_price", 16), Map.entry("low_stock_alert_at", 16), Map.entry("category", 16),
            Map.entry("barcode", 18),
            Map.entry("description", 26), Map.entry("vendor_sku", 18), Map.entry("ref", 12));

    /**
     * The worked examples at the top of a new template - ordinary-looking rows a person types
     * over. A row still exactly like one of these on upload is dropped as an example
     * ({@link #isShippedExample}); change any cell and it is a real product.
     */
    public static final List<Map<String, String>> EXAMPLE_ROWS = List.of(
            Map.of("name", "Rice (Mama Gold)", "sku", "RICE-50", "pack", "Bag", "contains", "50 kg",
                    "opening_stock", "12", "cost_price", "42000", "low_stock_alert_at", "3", "category", "Grains"),
            Map.of("name", "Bottled water 75cl", "sku", "WATER-75CL", "pack", "Pack", "contains", "12 x 750 ml",
                    "opening_stock", "40", "cost_price", "3600", "low_stock_alert_at", "10", "category", "Drinks"),
            Map.of("name", "Biro (blue)", "sku", "BIRO-BLUE", "contains", "piece",
                    "opening_stock", "200", "cost_price", "150", "low_stock_alert_at", "50", "category", "Office"));

    static final String EXAMPLES_NOTE = "The next " + EXAMPLE_ROWS.size() + " rows are examples - type over them "
            + "or delete them. Rows left exactly as they are here are ignored.";

    static final String HELP_TITLE = "Add your products";

    static final List<String> HELP_LINES = List.of(
            "One row per product. Only the product name is required.",
            "",
            "1.  Say what it is: Product name.",
            "2.  Say how you buy it: Comes in + Size of one - read together as \"Bag \u00b7 50 kg\" or "
                    + "\"Pack \u00b7 12 x 750 ml\".",
            "3.  (Optional) Say what you have today: How many you have now + Price you pay for one.",
            "4.  Upload it. We check everything and show you any problems before anything is saved.",
            "",
            "The grey row under the headings explains each column. You can leave it there.",
            "Already have your own spreadsheet? Upload that instead - we'll ask which column is which.",
            "The supplier on a row becomes that product's main supplier. Add more suppliers on the product page.");

    /** The template's columns for this company, as field keys. */
    public List<String> sheetFieldsFor(boolean isSeller, boolean skuAutoGenerated) {
        return SHEET_FIELDS.stream()
                .filter(field -> isSeller || !field.equals("unit_price"))
                .filter(field -> !skuAutoGenerated || !field.equals("sku"))
                .toList();
    }

    /**
     * Whether a row, read as field key to cell text, is one of {@link #EXAMPLE_ROWS} left exactly
     * as shipped: every example value matches (numbers by value, words ignoring case) and every
     * other column is blank.
     */
    public static boolean isShippedExample(Map<String, String> valuesByField) {
        for (Map<String, String> example : EXAMPLE_ROWS) {
            if (matchesExample(example, valuesByField)) {
                return true;
            }
        }
        return false;
    }

    private static boolean matchesExample(Map<String, String> example, Map<String, String> row) {
        boolean anyCompared = false;
        for (Map.Entry<String, String> cell : row.entrySet()) {
            String value = cell.getValue() == null ? "" : cell.getValue().trim();
            String expected = example.get(cell.getKey());
            if (expected == null) {
                if (!value.isEmpty()) {
                    return false;
                }
                continue;
            }
            if (!sameCell(expected, value)) {
                return false;
            }
            anyCompared = true;
        }
        return anyCompared && row.containsKey("name");
    }

    private static boolean sameCell(String expected, String actual) {
        Optional<BigDecimal> a = NumberValues.parseDecimal(expected);
        Optional<BigDecimal> b = NumberValues.parseDecimal(actual);
        if (a.isPresent() && b.isPresent()) {
            return a.get().compareTo(b.get()) == 0;
        }
        return expected.equalsIgnoreCase(actual);
    }

    /**
     * The pre-existing signature, kept so every caller that only knows about seller status still
     * compiles and behaves identically - it simply gets a template with no vendor dropdown, which
     * is exactly right for a caller that has not looked up a vendor directory.
     */
    public byte[] generateTemplate(boolean isSeller) {
        return generateTemplate(ProductTemplateContext.of(isSeller));
    }

    /**
     * The product sheet (BULK_IMPORT_CX_PLAN.md task 1.6): a help tab first, headers named for
     * people, a guidance row under them, a note and three worked examples, and dropdowns for what
     * it comes in, the supplier and the category. Starting stock and price are optional columns.
     */
    public byte[] generateTemplate(ProductTemplateContext context) {
        try (WorkbookBuilder builder = new WorkbookBuilder("Products")) {
            List<String> fields = sheetFieldsFor(context.isSeller(), context.skuAutoGenerated());
            writeSheetHeader(builder, fields);

            Row note = builder.sheet().createRow(2);
            Cell noteCell = note.createCell(0);
            noteCell.setCellValue(TemplateConventions.GUIDANCE_MARKER + " " + EXAMPLES_NOTE);
            noteCell.setCellStyle(builder.guidanceStyle());
            int rowIndex = 3;
            for (Map<String, String> example : EXAMPLE_ROWS) {
                Row row = builder.sheet().createRow(rowIndex++);
                for (int i = 0; i < fields.size(); i++) {
                    String value = example.get(fields.get(i));
                    if (value == null) {
                        continue;
                    }
                    Cell cell = row.createCell(i);
                    Optional<BigDecimal> number = isNumberField(fields.get(i)) ? NumberValues.parseDecimal(value) : Optional.empty();
                    if (number.isPresent()) {
                        cell.setCellValue(number.get().doubleValue());
                    } else {
                        cell.setCellValue(value);
                    }
                }
            }

            LookupSheetWriter lookups = new LookupSheetWriter(builder.workbook());
            addDropdown(builder, fields, "pack",
                    lookups.addList(PACKAGING_UNITS_RANGE, labelsOf(UnitOfMeasure.packagingUnits())),
                    "Comes in",
                    "Pick what it comes in - Bag, Carton, Keg. Leave it blank if you buy it loose.");
            addDropdown(builder, fields, "vendor_name",
                    lookups.addList(VENDOR_NAMES_RANGE, context.vendorDropdownNames()),
                    "Supplier",
                    "Pick one of your suppliers, or type a new name - we will ask whether to add it after you upload.");
            addDropdown(builder, fields, "category",
                    lookups.addList(CATEGORY_NAMES_RANGE, context.categoryNames()),
                    "Category",
                    "Pick one of your categories, or type a new one - we will add it.");
            lookups.hide();

            builder.addHelpSheet(HELP_TITLE, HELP_LINES);
            return builder.toBytes();
        }
    }

    private void writeSheetHeader(WorkbookBuilder builder, List<String> fields) {
        List<String> headers = fields.stream().map(SHEET_HEADERS::get).toList();
        Map<String, Integer> widths = new LinkedHashMap<>();
        fields.forEach(field -> widths.put(SHEET_HEADERS.get(field), SHEET_WIDTHS.get(field)));
        builder.writeHeaderRow(headers, widths, Map.of());
        builder.writeGuidanceRow(fields.stream().map(SHEET_GUIDANCE::get).toList());
        applyNumberFormats(builder, fields);
    }

    private static boolean isNumberField(String field) {
        return Set.of("opening_stock", "cost_price", "unit_price", "low_stock_alert_at").contains(field);
    }

    public byte[] exportProducts(List<Product> products) {
        return exportProducts(products, Map.of(), true);
    }

    /** The exported columns for this tenant: the template's, plus the hidden Ref. */
    static List<String> exportFieldsFor(boolean isSeller) {
        return EXPORT_FIELDS.stream().filter(field -> isSeller || !field.equals("unit_price")).toList();
    }

    /**
     * @param preferredVendorsByProductId supplies the three vendor columns. Passed in already
     *     resolved rather than read off {@code Product.getVendors()} here, because that
     *     association is LAZY specifically so a page of products never pays to load it - see its
     *     javadoc, and {@code ProductManagementService.preferredVendorNamesFor} for the batched
     *     query that fills this map in one round trip instead of one per row. A product missing
     *     from the map simply exports with blank vendor columns.
     * @param isSeller whether to carry the selling price column, on the same rule the template
     *     uses. A buying company has no selling price to give, so exporting the column for them
     *     hands back a sheet their own import then reports as a column it does not recognise -
     *     "Download my products", edit, upload is the workflow this file exists for, and it has to
     *     round-trip without a question the user cannot answer.
     */
    public byte[] exportProducts(
            List<Product> products, Map<UUID, ProductVendorSnapshot> preferredVendorsByProductId, boolean isSeller) {
        List<String> fields = exportFieldsFor(isSeller);
        try (WorkbookBuilder builder = new WorkbookBuilder("Products")) {
            // The same columns and words as the template, so an exported sheet can be edited and
            // uploaded again through the import page.
            writeSheetHeader(builder, fields);
            builder.hideColumn(fields.indexOf("ref"));
            Sheet sheet = builder.sheet();

            int rowIndex = 2;
            for (Product product : products) {
                Row row = sheet.createRow(rowIndex++);
                // Indexed by header name rather than by literal position. The positions moved
                // with UNIT_UX_CONTRACT.md section 9's regrouping, and a block of hand-counted
                // integers is exactly the thing that silently writes the cost price into the
                // opening-stock column the next time they move.
                cell(fields, row, "name").setCellValue(product.getName());
                cell(fields, row, "sku").setCellValue(product.getSku());
                cell(fields, row, "description")
                        .setCellValue(product.getDescription() == null ? "" : product.getDescription());
                // Labels, not the stored codes - contract section 7, non-negotiable 4. The export
                // and the template are the same file to a user who exports, edits and re-uploads,
                // so a cell that reads "KG" on one and "Kilogram (kg)" on the other would be two
                // vocabularies in one workflow. Round-trips exactly: fromCodeOrLabel resolves the
                // display label back to the same constant.
                cell(fields, row, "pack").setCellValue(unitLabelOrBlank(product.getPackagingUnit()));
                // One phrase, the same shape the user types - PackContents.format. Never the
                // "12 x 750" form: only the product is stored, so reconstructing the factors
                // would invent a fact about their packaging.
                cell(fields, row, "contains")
                        .setCellValue(PackContents.format(product.getPackagingSize(), product.getUnitOfMeasure()));

                // Both quantities are exported in the terms the column is now READ in - packs
                // when the product has one (section 9.1), stock units when it does not. This is
                // the whole of what keeps "export, edit, re-upload" honest: the stored figure is
                // 1,500 ml, the column means kegs, so the cell has to say 30. Writing 1,500 there
                // would re-import as 1,500 kegs and multiply the catalog by fifty on every round
                // trip - the same trap the deleted opening_stock_counted_in column was left blank
                // to avoid, solved now by stating the number in the column's own unit instead of
                // by leaving a second column empty.
                BigDecimal openingStock = inSheetUnits(product, BigDecimal.valueOf(product.getQuantityOnHand()));
                cell(fields, row, "opening_stock").setCellValue(openingStock.doubleValue());
                if (product.getLowStockThreshold() != null) {
                    BigDecimal alertAt =
                            inSheetUnits(product, BigDecimal.valueOf(product.getLowStockThreshold()));
                    cell(fields, row, "low_stock_alert_at").setCellValue(alertAt.doubleValue());
                }

                // cost_price gets the same treatment as the two quantities above, for the same
                // reason: it is written in the terms the column is READ in. Since section 9.2 was
                // amended, that is PER PACK - "what you pay for one keg" - while what is STORED
                // stays per stock unit, which is what actually delivers the comparability across
                // suppliers the old rule was reaching for. See
                // ProductCatalogRowHandler.perStockUnitPriceOf for the reading half.
                //
                // This comment previously said the opposite ("per stock unit on the way out
                // because it is per stock unit on the way in") and the code matched it. That was
                // true before the amendment and silently wrong after it: a product stored at
                // N900/kg in 50 kg bags exported 900, re-imported as N900 PER BAG, and came back
                // N18/kg - a 50x loss, on a row the review screen marked VALID with no warning,
                // while the quantity beside it round-tripped perfectly and hid it. Exporting,
                // editing and re-uploading is the workflow this method exists to serve, so a
                // basis it does not share with the parser is not a cosmetic mismatch.
                // The main supplier's last price where there is one - what "Price you pay for one"
                // means, and what an unchanged re-upload writes back unchanged. The product's
                // average cost otherwise.
                ProductVendorSnapshot priced = preferredVendorsByProductId.get(product.getId());
                BigDecimal perStockUnitCost = priced != null && priced.lastCostPrice() != null
                        ? priced.lastCostPrice()
                        : product.getCostPrice();
                if (perStockUnitCost != null) {
                    cell(fields, row, "cost_price").setCellValue(inSheetPrice(product, perStockUnitCost).doubleValue());
                }
                // Nullable since V17 (a buying company's product has no selling price to give)
                // - null-guarded the same way costPrice above it always has been, so an export
                // of a company's own catalog does not NPE on a row with nothing in this column.
                if (product.getUnitPrice() != null && fields.contains("unit_price")) {
                    cell(fields, row, "unit_price").setCellValue(product.getUnitPrice().doubleValue());
                }

                cell(fields, row, "ref").setCellValue(ProductRefs.encode(product.getId()));
                if (product.getCompanyCategory() != null) {
                    cell(fields, row, "category").setCellValue(product.getCompanyCategory().getName());
                }
                ProductVendorSnapshot vendor = preferredVendorsByProductId.get(product.getId());
                if (vendor != null) {
                    cell(fields, row, "vendor_name").setCellValue(vendor.vendorName() == null ? "" : vendor.vendorName());
                    cell(fields, row, "vendor_sku").setCellValue(vendor.vendorSku() == null ? "" : vendor.vendorSku());
                }
            }
            return builder.toBytes();
        }
    }


    /**
     * Which unit the two quantity columns are counted in for a row declaring these three
     * counting values - section 9.1's rule, expressed as section 2.1's set rather than as a
     * fresh {@code if}.
     *
     * <p>"The pack when the row has one, the stock unit when it does not" is precisely
     * {@code UnitOptions.defaultOption}: section 2.1 defines {@code isDefault} as the product's
     * own pack if it has one, else the stock unit. Asking the set instead of re-deriving the
     * rule is what stops this sheet and the product form from ever disagreeing about what a
     * number means - the single failure this whole remediation exists to undo.
     *
     * <p>Never empty: a row with no stock unit at all still yields the one-entry "units" set
     * (section 2.1's last paragraph, the pre-V17 product), whose factor is 1.
     */
    private UnitOption countedIn(String stockUnitCode, String packagingUnit, BigDecimal unitsPerPack) {
        List<UnitOption> options = UnitOptions.forProduct(stockUnitCode, packagingUnit, unitsPerPack);
        return UnitOptions.defaultOption(options)
                .or(() -> UnitOptions.stockUnitOption(options))
                .orElseGet(() -> new UnitOption(
                        UnitOptions.NO_STOCK_UNIT_CODE, UnitOptions.NO_STOCK_UNIT_LABEL,
                        BigDecimal.ONE, true, true, false));
    }

    /**
     * A stored stock-unit figure expressed in the terms the sheet's quantity columns are read in
     * - the inverse of {@link #packAwareQuantity}, for the export.
     *
     * <p>Dividing rather than multiplying is the one place this class does arithmetic that
     * {@code UnitOption} does not already own, and the reason is that no ledger value is ever
     * computed from it: the result is written into a spreadsheet cell and read back through
     * {@link #packAwareQuantity}, which multiplies by the same factor. Six decimal places is
     * enough for that to round-trip exactly - 1,501 ml in 50 ml kegs exports as 30.02 and
     * re-imports as 1,501 - and a non-terminating quotient comes back within half a stock unit,
     * which HALF_UP then resolves to the original figure.
     */
    private BigDecimal inSheetUnits(Product product, BigDecimal stockUnits) {
        UnitOption option =
                countedIn(product.getUnitOfMeasure(), product.getPackagingUnit(), product.getPackagingSize());
        if (option.factorToStockUnit().compareTo(BigDecimal.ONE) == 0) {
            return stockUnits;
        }
        return stockUnits.divide(option.factorToStockUnit(), 6, java.math.RoundingMode.HALF_UP)
                .stripTrailingZeros();
    }

    /**
     * The price twin of {@link #inSheetUnits}: a stored per-stock-unit cost expressed per PACK,
     * which is the basis the {@code cost_price} column is read in (section 9.2 as amended, and
     * {@code ProductCatalogRowHandler.perStockUnitPriceOf}).
     *
     * <p>Multiplying rather than dividing, and for the mirror-image reason: a price is per-unit,
     * so a bigger unit carries a bigger number. {@code UnitOption.toStockUnitPrice} divides by
     * this same factor on the way back in, so the pair round-trips - N900/kg over a 50 kg bag
     * exports as 45,000 and re-imports as 900.
     *
     * <p>Scale 6 before the cell, matching the contract's "do the arithmetic at scale 6 first";
     * the factor-of-1 case returns the input unchanged, exactly as {@code toStockUnitPrice} does,
     * so a product with no pack exports byte-for-byte what it always has.
     */
    private BigDecimal inSheetPrice(Product product, BigDecimal perStockUnit) {
        UnitOption option =
                countedIn(product.getUnitOfMeasure(), product.getPackagingUnit(), product.getPackagingSize());
        if (option.factorToStockUnit().compareTo(BigDecimal.ONE) == 0) {
            return perStockUnit;
        }
        return perStockUnit.multiply(option.factorToStockUnit())
                .setScale(6, java.math.RoundingMode.HALF_UP)
                .stripTrailingZeros();
    }

    /**
     * One export cell, addressed by header name rather than by a hand-counted index. The column
     * list is passed in because it is not fixed: a buying company's export has no selling price
     * column, so every index to the right of it moves.
     */
    private Cell cell(List<String> fields, Row row, String field) {
        int column = fields.indexOf(field);
        if (column < 0) {
            throw new IllegalStateException("No " + field + " column on this export: " + fields);
        }
        return row.createCell(column);
    }

    /**
     * The headline case, and the one the whole sheet turns on: <b>a pack of twelve 750 ml bottles
     * of water</b>, counted in BOTTLE, with 30 in {@code opening_stock} - thirty PACKS, 360
     * bottles (UNIT_UX_CONTRACT.md section 9.1).
     *
     * <h2>Why this row was rewritten - PACK_ENTRY_REDESIGN.md section 8.7</h2>
     * The previous version of this row was {@code stock_unit=Milliliter (ml)},
     * {@code pack=Keg}, {@code units_per_pack=50}, on a product called "Sample Widget". Read it
     * as somebody learning the pattern: <em>put the measure in stock_unit, the container in pack,
     * the number in units_per_pack.</em> Apply that to a pack of bottled water and you get
     * {@code ml, Pack, 750} - which is exactly the defect that was reported, and it is this row,
     * followed correctly. The customer was not confused; they imitated the template, which is the
     * most reliable thing a spreadsheet user does.
     *
     * <p>Two things made the old row impossible to check. "Sample Widget" is not a real thing, so
     * "a keg of 50 ml of Widget" cannot be recognised as odd - an example whose numbers cannot be
     * checked against the world teaches its SHAPE and nothing else, and the shape was the wrong
     * part. And it was the only packed example, so the sole demonstration of how packs work was
     * the misleading one.
     *
     * <h2>The stock unit is ml, not Bottle - and that is the correction</h2>
     * A container word is never a stock unit. The same water bought as a 750 ml bottle today and
     * a 2 L keg tomorrow is ONE product with one balance, and {@code unitOfMeasure} is immutable
     * once stock moves - so "Bottle" as the stock unit would force a second product for the same
     * water. The substance is the unit; every container is a pack sized in it. Tomorrow's keg is
     * another pack on this same row ({@code ProductVendorPack}), not another product.
     *
     * <h2>Why these numbers</h2>
     * Nobody reads a header comment twice, but everybody looks at the row above the one they are
     * filling in, so this row is written to be unreadable in any other way:
     * <ul>
     *   <li>{@code pack} is <b>Bottle</b> - the word that was missing. Before section 4 added it
     *       there was no container called a bottle at all, so a 750 ml bottle could only be
     *       described as a Pack, a Box or a Keg, and the picker could not say what was in the
     *       user's hand. That absence is what pushed the 750 into the wrong column.
     *   <li>{@code units_per_pack} is <b>750</b> and it is CORRECT here, because the container
     *       named beside it really does hold 750 ml. The reported defect was the same 750 beside
     *       <em>Pack</em>, which does not.
     *   <li>{@code opening_stock} is <b>30</b> - thirty bottles, 22,500 ml - showing section 9.1's
     *       rule. {@code low_stock_alert_at} is 5, five bottles, showing the second column follows
     *       it too.
     *   <li>{@code cost_price} is what one PACK costs, which the header says and section 9.2
     *       requires.
     * </ul>
     *
     * <p>See {@link #exampleRowTwo} for the case where a measure genuinely IS the stock unit, and
     * {@link #exampleRowThree} for the no-pack shape. The three together draw the line this
     * template exists to teach without a word of explanation.
     *
     * <p>When the tenant has suppliers on file, the first one is used to demonstrate the vendor
     * columns with a name the user will actually recognise. When they have none, those columns are
     * left blank rather than filled with an invented supplier - an example row naming a company
     * that does not exist would be the one example that teaches the wrong thing.
     */
    private void applyNumberFormats(WorkbookBuilder builder, List<String> headers) {
        for (int i = 0; i < headers.size(); i++) {
            switch (headers.get(i)) {
                case "unit_price", "cost_price" -> builder.formatColumn(i, builder.moneyStyle());
                // opening_stock and low_stock_alert_at moved from the whole-number format to the
                // optional-decimals one with UNIT_UX_CONTRACT.md section 9.1: they count PACKS
                // now, and "30.5 kegs" is an ordinary shelf that the thousands-integer format
                // would have displayed as 31 while storing 30.5 - a cell that disagrees with
                // itself is worse than no formatting at all.
                case "opening_stock", "low_stock_alert_at", "contains" ->
                        builder.formatColumn(i, builder.decimalStyle());
                default -> {
                    // Text columns keep the General format. Deliberately including sku: forcing a
                    // format on it would turn a numeric-looking SKU like 00123 into 123.
                }
            }
        }
    }

    private void addDropdown(
            WorkbookBuilder builder, List<String> headers, String header, String definedName, String title, String text) {
        int columnIndex = headers.indexOf(header);
        if (columnIndex >= 0) {
            builder.addDropdown(columnIndex, definedName, title, text);
        }
    }

    /**
     * Dropdown entries and exported cells are human labels - {@code "Kilogram (kg)"},
     * {@code "Bag"} - never the internal codes {@code KG} and {@code BAG}. Contract section 7,
     * non-negotiable 4: no spreadsheet cell contains an internal code. This rule was already
     * honoured in the web UI and broken in the artifact users spend their time in
     * (UNIT_UX_REMEDIATION_PLAN.md P3-4).
     *
     * <p>Safe in both directions because {@code UnitOfMeasure.fromCodeOrLabel} has always accepted
     * the display label verbatim - {@code UnitOfMeasureAliases} derives it from
     * {@link UnitOfMeasure#label()} rather than listing it, so the two can never drift.
     */
    private List<String> labelsOf(List<UnitOfMeasure> units) {
        return units.stream().map(UnitOfMeasure::label).toList();
    }

    /**
     * A stored unit code as the label a person reads, or blank when the product has no unit set -
     * the pre-V17 row that never got one. Falls back to the code itself for a value that is somehow
     * not on the fixed list, because dropping it would silently empty a column on a round trip.
     */
    private String unitLabelOrBlank(String code) {
        if (code == null) {
            return "";
        }
        return UnitOfMeasure.fromCode(code).map(UnitOfMeasure::label).orElse(code);
    }

}
