-- Seed fixed permissions, fixed roles, and the V1 role -> permission mapping.
-- Looked up by code/name (not hardcoded UUIDs) since ids are generated by gen_random_uuid().

INSERT INTO permissions (code, description) VALUES
    ('MANAGE_USERS',     'Create, update, deactivate, and assign roles to tenant users'),
    ('MANAGE_PRODUCTS',  'Create, update, and deactivate products'),
    ('MANAGE_INVENTORY', 'Record stock movements and adjust inventory levels'),
    ('VIEW_ANALYTICS',   'View inventory and sales analytics/reports'),
    ('MANAGE_ROLES',     'Manage role-to-permission assignments');

INSERT INTO roles (name, description) VALUES
    ('ADMIN',   'Full access to all tenant features and settings'),
    ('MANAGER', 'Manage products, inventory, and view analytics'),
    ('STAFF',   'Manage day-to-day inventory operations');

-- ADMIN -> all permissions
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
CROSS JOIN permissions p
WHERE r.name = 'ADMIN';

-- MANAGER -> MANAGE_PRODUCTS, MANAGE_INVENTORY, VIEW_ANALYTICS
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code IN ('MANAGE_PRODUCTS', 'MANAGE_INVENTORY', 'VIEW_ANALYTICS')
WHERE r.name = 'MANAGER';

-- STAFF -> MANAGE_INVENTORY
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code = 'MANAGE_INVENTORY'
WHERE r.name = 'STAFF';
