package com.procurepal_services.stock_bridge_api.product.bulk;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.assertj.core.api.Assertions.catchThrowableOfType;

import com.procurepal_services.stock_bridge_api.imports.io.ImportLimits;
import com.procurepal_services.stock_bridge_api.imports.io.LookupSheetWriter;
import com.procurepal_services.stock_bridge_api.imports.io.SpreadsheetReader;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.stream.IntStream;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Name;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.xssf.usermodel.XSSFDataValidation;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.junit.jupiter.api.Test;
import org.springframework.mock.web.MockMultipartFile;

/**
 * The product template and its parser, tested against each other and against the written file
 * itself. No Spring: {@link ProductExcelService} takes one collaborator, and constructing it
 * directly keeps these fast enough to run on every save.
 *
 * <h2>Why several of these read the generated bytes back with POI</h2>
 * A data validation that silently failed to attach is invisible to a test that checks cell values -
 * the file opens, the columns are right, the examples are there, and the dropdown the whole feature
 * was for simply is not. It is the classic failure of generating spreadsheets, and the only way to
 * catch it is to read the validation records out of the written file and assert on them, which is
 * what {@link #everyIntendedColumnReallyHasADropdownInTheWrittenFile} does.
 */
class ProductExcelServiceTest {

    private final ProductExcelService service = new ProductExcelService(new SpreadsheetReader());

    private static final List<String> VENDORS =
            List.of("Dangote Nigeria Plc", "Ade Foods Ltd", "Olam Agri Nigeria");

    // ------------------------------------------------------------------------------- columns ----

    /**
     * The frozen column vocabulary of BULK_IMPORT_CONTRACT.md section 5, in order. The first ten
     * are the stability promise tenants have saved copies of; the last three are section 7.1's
     * additions, appended rather than inserted for exactly that reason.
     */
    @Test
    void theSellerTemplateCarriesEveryContractColumnInOrder() {
        List<String> headers = headersOf(service.generateTemplate(new ProductTemplateContext(true, VENDORS)));

        assertThat(headers).containsExactly(
                "name", "sku", "description", "unit_price", "cost_price", "quantity_on_hand",
                "low_stock_threshold", "unit_of_measure", "packaging_unit", "packaging_size",
                "vendor_name", "vendor_sku", "is_preferred_vendor");
    }

    /** A buying company has no selling price at all, so the column is absent rather than optional. */
    @Test
    void theCompanyTemplateDropsUnitPriceAndKeepsEverythingElseInPlace() {
        List<String> headers = headersOf(service.generateTemplate(new ProductTemplateContext(false, VENDORS)));

        assertThat(headers).doesNotContain("unit_price");
        assertThat(headers).containsSequence("cost_price", "quantity_on_hand");
        assertThat(headers).containsSequence("vendor_name", "vendor_sku", "is_preferred_vendor");
    }

    // ------------------------------------------------------------ the lookup sheet and ranges ----

    /**
     * Hidden, present, and pointing at real values. Hidden rather than deleted after the names are
     * defined: a name pointing at a missing sheet resolves to {@code #REF!} and Excel then shows an
     * empty dropdown, which is worse than none because the column still looks like it has one.
     */
    @Test
    void theLookupSheetIsPresentHiddenAndItsNamedRangesResolveToTheRealValues() {
        byte[] file = service.generateTemplate(new ProductTemplateContext(true, VENDORS));

        try (XSSFWorkbook workbook = open(file)) {
            int lookupIndex = workbook.getSheetIndex(LookupSheetWriter.SHEET_NAME);
            assertThat(lookupIndex).as("the _lookups sheet must exist").isNotNegative();
            assertThat(workbook.isSheetHidden(lookupIndex)).as("_lookups must be hidden").isTrue();
            // The data sheet must stay first: every reader in this codebase takes sheet zero.
            assertThat(workbook.getSheetAt(0).getSheetName()).isEqualTo("Products");

            assertThat(valuesOfNamedRange(workbook, "base_units"))
                    .contains("KG", "LITER", "PIECE")
                    .doesNotContain("BAG", "CARTON");
            assertThat(valuesOfNamedRange(workbook, "packaging_units"))
                    .contains("BAG", "CARTON", "DRUM")
                    .doesNotContain("KG");
            assertThat(valuesOfNamedRange(workbook, "vendor_names"))
                    .containsExactlyElementsOf(VENDORS);
            assertThat(valuesOfNamedRange(workbook, "yes_flag")).containsExactly("TRUE");
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    /**
     * The test the whole dropdown feature lives or dies on: the validation records are read back out
     * of the written file, and each one is checked for the column it covers AND the named range it
     * points at. A formula constraint naming a range that was never defined would produce an empty
     * dropdown at open time and nothing at all at write time.
     */
    @Test
    void everyIntendedColumnReallyHasADropdownInTheWrittenFile() {
        byte[] file = service.generateTemplate(new ProductTemplateContext(true, VENDORS));

        try (XSSFWorkbook workbook = open(file)) {
            XSSFSheet sheet = workbook.getSheetAt(0);
            List<String> headers = headersOf(file);
            Map<String, String> rangeByColumn = dropdownRangesByColumn(sheet, headers);

            assertThat(rangeByColumn)
                    .containsEntry("unit_of_measure", "base_units")
                    .containsEntry("packaging_unit", "packaging_units")
                    .containsEntry("vendor_name", "vendor_names")
                    .containsEntry("is_preferred_vendor", "yes_flag");

            // And every one of those names is actually defined, or the dropdown resolves to #REF!.
            rangeByColumn.values().forEach(range ->
                    assertThat(workbook.getName(range)).as("defined name %s", range).isNotNull());

            // Deliberately no dropdowns on free-text and numeric columns - section 5.2's last line.
            assertThat(rangeByColumn.keySet())
                    .doesNotContain("sku", "name", "description", "unit_price", "cost_price",
                            "quantity_on_hand", "low_stock_threshold", "packaging_size", "vendor_sku");
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    /** The dropdown must cover the rows the user will paste into, not just the example rows. */
    @Test
    void dropdownsCoverTheWholeImportableRange() {
        byte[] file = service.generateTemplate(new ProductTemplateContext(true, VENDORS));

        try (XSSFWorkbook workbook = open(file)) {
            XSSFDataValidation validation = (XSSFDataValidation) workbook.getSheetAt(0).getDataValidations().stream()
                    .filter(v -> v.getValidationConstraint().getFormula1().equals("base_units"))
                    .findFirst()
                    .orElseThrow();

            assertThat(validation.getRegions().getCellRangeAddress(0).getFirstRow()).isEqualTo(1);
            assertThat(validation.getRegions().getCellRangeAddress(0).getLastRow())
                    .isEqualTo(ImportLimits.MAX_ROWS);
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    /**
     * Past the cap the column is free text rather than a truncated list - an arbitrary first 200 of
     * 900 vendors is a dropdown missing the one this user needs, which reads as "your supplier is
     * not in the system".
     */
    @Test
    void aVendorListPastTheCapLeavesTheColumnAsFreeText() {
        List<String> tooMany = IntStream.range(0, ImportLimits.VENDOR_DROPDOWN_CAP + 1)
                .mapToObj(i -> "Supplier " + i)
                .toList();

        byte[] file = service.generateTemplate(new ProductTemplateContext(true, tooMany));

        try (XSSFWorkbook workbook = open(file)) {
            Map<String, String> rangeByColumn = dropdownRangesByColumn(workbook.getSheetAt(0), headersOf(file));
            assertThat(rangeByColumn).doesNotContainKey("vendor_name");
            // The unit dropdowns are unaffected - one column losing its list must not take the
            // others with it.
            assertThat(rangeByColumn).containsKey("unit_of_measure");
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    /** A tenant with no suppliers yet gets no vendor dropdown, and no empty one either. */
    @Test
    void aTenantWithNoVendorsGetsNoVendorDropdown() {
        byte[] file = service.generateTemplate(ProductTemplateContext.of(false));

        try (XSSFWorkbook workbook = open(file)) {
            assertThat(dropdownRangesByColumn(workbook.getSheetAt(0), headersOf(file)))
                    .doesNotContainKey("vendor_name");
            assertThat(workbook.getName("vendor_names")).isNull();
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    // --------------------------------------------------------------- comments, formats, panes ----

    /**
     * Section 7.2's replacement of the single paragraph on B1: one short comment per column, where
     * the question is actually asked.
     */
    @Test
    void everyColumnCarriesItsOwnHeaderComment() {
        byte[] file = service.generateTemplate(new ProductTemplateContext(true, VENDORS));

        try (XSSFWorkbook workbook = open(file)) {
            Row header = workbook.getSheetAt(0).getRow(0);
            for (Cell cell : header) {
                assertThat(cell.getCellComment())
                        .as("comment on column %s", cell.getStringCellValue())
                        .isNotNull();
                assertThat(cell.getCellComment().getString().getString())
                        .as("comment on column %s", cell.getStringCellValue())
                        .isNotBlank();
            }
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    /** Number formats, so a user typing 45,000 gets a number and not a string the parser has to rescue. */
    @Test
    void priceAndQuantityColumnsCarryNumberFormats() {
        byte[] file = service.generateTemplate(new ProductTemplateContext(true, VENDORS));

        try (XSSFWorkbook workbook = open(file)) {
            XSSFSheet sheet = workbook.getSheetAt(0);
            List<String> headers = headersOf(file);

            assertThat(formatOfColumn(sheet, headers.indexOf("unit_price"))).isEqualTo("#,##0.00");
            assertThat(formatOfColumn(sheet, headers.indexOf("cost_price"))).isEqualTo("#,##0.00");
            assertThat(formatOfColumn(sheet, headers.indexOf("quantity_on_hand"))).isEqualTo("#,##0");
            // sku stays General on purpose: a number format would turn 00123 into 123.
            assertThat(formatOfColumn(sheet, headers.indexOf("sku"))).isEqualTo("General");
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    @Test
    void theHeaderRowIsFrozen() {
        byte[] file = service.generateTemplate(ProductTemplateContext.of(false));

        try (XSSFWorkbook workbook = open(file)) {
            assertThat(workbook.getSheetAt(0).getPaneInformation().getHorizontalSplitPosition()).isEqualTo((short) 1);
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    // ------------------------------------------------------------------------- the round trip ----

    /**
     * The template, filled in the way a user would fill it, read back by the parser that owns it.
     * This is the assertion that the generator and the parser have not drifted - separately correct
     * halves that disagree about a column would pass every other test in this file.
     */
    @Test
    void aFilledInTemplateRoundTripsThroughItsOwnParser() {
        byte[] template = service.generateTemplate(new ProductTemplateContext(false, VENDORS));
        byte[] filled = fillIn(template, List.of(
                Map.of("name", "Rice 50kg", "sku", "RICE-50", "cost_price", "42000",
                        "quantity_on_hand", "40", "unit_of_measure", "KG", "packaging_unit", "BAG",
                        "packaging_size", "50", "vendor_name", "Dangote Nigeria Plc",
                        "vendor_sku", "DN-RICE-50", "is_preferred_vendor", "TRUE"),
                Map.of("name", "Groundnut Oil 5L", "sku", "OIL-5L", "unit_of_measure", "LITER")));

        List<ParsedProductRow> rows = service.parse(multipart("products.xlsx", filled), false);

        assertThat(rows).hasSize(2);
        ParsedProductRow rice = rows.get(0);
        assertThat(rice.sku()).isEqualTo("RICE-50");
        assertThat(rice.costPrice()).isEqualByComparingTo("42000");
        assertThat(rice.quantityOnHand()).isEqualTo(40);
        assertThat(rice.unitOfMeasure()).isEqualTo("KG");
        assertThat(rice.packagingUnit()).isEqualTo("BAG");
        assertThat(rice.packagingSize()).isEqualByComparingTo("50");
        assertThat(rice.vendorName()).isEqualTo("Dangote Nigeria Plc");
        assertThat(rice.vendorSku()).isEqualTo("DN-RICE-50");
        assertThat(rice.preferredVendor()).isTrue();
        // The example rows the template ships with are skipped, not parsed - a user who forgets to
        // delete them gets no errors for them.
        assertThat(rows).extracting(ParsedProductRow::sku).doesNotContain("EXAMPLE-SKU-DELETE-ME-1");

        ParsedProductRow oil = rows.get(1);
        assertThat(oil.unitOfMeasure()).isEqualTo("LITER");
        assertThat(oil.packagingUnit()).isNull();
        assertThat(oil.vendorName()).isNull();
        assertThat(oil.preferredVendor()).isFalse();
    }

    /** The same content as a CSV must parse to the same rows - the format is the user's choice, not ours. */
    @Test
    void aCsvOfTheSameContentParsesToTheSameRows() {
        byte[] csv = ("name,sku,cost_price,quantity_on_hand,unit_of_measure,packaging_unit,packaging_size,"
                        + "vendor_name,vendor_sku,is_preferred_vendor\n"
                        + "Rice 50kg,RICE-50,42000,40,KG,BAG,50,Dangote Nigeria Plc,DN-RICE-50,TRUE\n")
                .getBytes(StandardCharsets.UTF_8);

        List<ParsedProductRow> rows = service.parse(multipart("products.csv", csv), false);

        assertThat(rows).hasSize(1);
        assertThat(rows.get(0).sku()).isEqualTo("RICE-50");
        assertThat(rows.get(0).unitOfMeasure()).isEqualTo("KG");
        assertThat(rows.get(0).packagingUnit()).isEqualTo("BAG");
        assertThat(rows.get(0).vendorName()).isEqualTo("Dangote Nigeria Plc");
        assertThat(rows.get(0).preferredVendor()).isTrue();
    }

    // ------------------------------------------------------------------- forgiveness on parse ----

    /**
     * The point of the whole alias table, seen from the outside: a file typed rather than picked
     * still imports, and produces the normalized CODE rather than whatever the user wrote.
     */
    @Test
    void typedUnitSpellingsAreAcceptedAndNormalizedToCodes() {
        List<ParsedProductRow> rows = service.parse(multipart("products.csv", csv(
                "name,sku,unit_of_measure,packaging_unit,packaging_size\n"
                        + "Rice 50kg,RICE-50,kilogram,bags,50\n"
                        + "Palm Oil,OIL-25,litres,jerrycan,25\n")), false);

        assertThat(rows).extracting(ParsedProductRow::unitOfMeasure).containsExactly("KG", "LITER");
        assertThat(rows).extracting(ParsedProductRow::packagingUnit).containsExactly("BAG", "KEG");
    }

    /** And the money people actually type - the comma is a thousands separator here, not a typo. */
    @Test
    void formattedMoneyAndQuantitiesAreUnderstood() {
        List<ParsedProductRow> rows = service.parse(multipart("products.csv", csv(
                "name,sku,cost_price,quantity_on_hand\nRice 50kg,RICE-50,\"N45,000.00\",\"1,200\"\n")), false);

        assertThat(rows.get(0).costPrice()).isEqualByComparingTo("45000.00");
        assertThat(rows.get(0).quantityOnHand()).isEqualTo(1200);
    }

    /**
     * A code from the wrong half of the catalog is still rejected - the role split is what removes
     * the "50kg bag" ambiguity - but the message now names the column it does belong in, instead of
     * claiming we do not recognise a value we plainly do.
     */
    @Test
    void aPackagingCodeInTheBaseUnitColumnIsRejectedWithAHintNamingTheRightColumn() {
        BulkUploadValidationException thrown = catchThrowableOfType(
                BulkUploadValidationException.class,
                () -> service.parse(multipart("products.csv", csv(
                        "name,sku,unit_of_measure\nRice 50kg,RICE-50,BAG\n")), false));

        assertThat(thrown.getErrors()).singleElement().satisfies(error -> {
            assertThat(error.row()).isEqualTo(2);
            assertThat(error.column()).isEqualTo("unit_of_measure");
            assertThat(error.message()).contains("BAG").contains("not a recognized unit of measure");
            assertThat(error.message()).contains("packaging_unit");
        });
    }

    /** A vendor SKU with no vendor named is not a partly-filled row; it is a row we cannot interpret. */
    @Test
    void vendorSkuAndPreferredFlagRequireAVendorName() {
        BulkUploadValidationException thrown = catchThrowableOfType(
                BulkUploadValidationException.class,
                () -> service.parse(multipart("products.csv", csv(
                        "name,sku,vendor_sku,is_preferred_vendor\nRice 50kg,RICE-50,DN-1,TRUE\n")), false));

        assertThat(thrown.getErrors()).extracting(ProductRowError::column)
                .containsExactlyInAnyOrder("vendor_sku", "is_preferred_vendor");
    }

    /** TRUE is what the dropdown offers; everything a person would write instead means the same thing. */
    @Test
    void thePreferredFlagAcceptsEveryReasonableSpellingOfYes() {
        List<ParsedProductRow> rows = service.parse(multipart("products.csv", csv(
                "name,sku,vendor_name,is_preferred_vendor\n"
                        + "A,SKU-1,Dangote Nigeria Plc,TRUE\n"
                        + "B,SKU-2,Dangote Nigeria Plc,yes\n"
                        + "C,SKU-3,Dangote Nigeria Plc,Y\n"
                        + "D,SKU-4,Dangote Nigeria Plc,1\n"
                        + "E,SKU-5,Dangote Nigeria Plc,\n"
                        + "F,SKU-6,Dangote Nigeria Plc,no\n")), false);

        assertThat(rows).extracting(ParsedProductRow::preferredVendor)
                .containsExactly(true, true, true, true, false, false);
    }

    // ----------------------------------------------------------------- limits and file errors ----

    /**
     * The over-cap rejection reaches the caller as a file-level row-0 error carrying the real
     * number, not as a parse failure and not after a full parse.
     */
    @Test
    void anOverCapFileIsRejectedWithTheRealRowCountBeforeAnyRowIsValidated() {
        StringBuilder content = new StringBuilder("name,sku,unit_of_measure\n");
        for (int i = 0; i < 5100; i++) {
            // Every row also carries an invalid unit. If the cap were enforced after parsing,
            // these would come back as 5,100 row errors instead of one file error.
            content.append("Product ").append(i).append(",SKU-").append(i).append(",NOT-A-UNIT\n");
        }

        BulkUploadValidationException thrown = catchThrowableOfType(
                BulkUploadValidationException.class,
                () -> service.parse(multipart("products.csv", csv(content.toString())), false));

        assertThat(thrown.getErrors()).singleElement().satisfies(error -> {
            assertThat(error.row()).isZero();
            assertThat(error.column()).isEqualTo("file");
            assertThat(error.message()).contains("5,100 rows").contains("the limit is 5,000");
        });
    }

    @Test
    void garbageStillSaysTheFileIsNotAValidXlsx() {
        assertThatThrownBy(() -> service.parse(multipart("products.xlsx", csv("nonsense")), false))
                .isInstanceOf(BulkUploadValidationException.class)
                .satisfies(e -> assertThat(((BulkUploadValidationException) e).getErrors())
                        .singleElement()
                        .satisfies(error -> assertThat(error.message())
                                .isEqualTo("The uploaded file is not a valid .xlsx file")));
    }

    // ------------------------------------------------------------------------------ fixtures ----

    private MockMultipartFile multipart(String filename, byte[] content) {
        return new MockMultipartFile("file", filename, "application/octet-stream", content);
    }

    private byte[] csv(String content) {
        return content.getBytes(StandardCharsets.UTF_8);
    }

    private List<String> headersOf(byte[] file) {
        try (XSSFWorkbook workbook = open(file)) {
            List<String> headers = new ArrayList<>();
            for (Cell cell : workbook.getSheetAt(0).getRow(0)) {
                headers.add(cell.getStringCellValue());
            }
            return headers;
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    /** Reads the validation records back out and maps each covered column to the range it points at. */
    private Map<String, String> dropdownRangesByColumn(XSSFSheet sheet, List<String> headers) {
        Map<String, String> byColumn = new java.util.LinkedHashMap<>();
        for (XSSFDataValidation validation : sheet.getDataValidations()) {
            String formula = validation.getValidationConstraint().getFormula1();
            for (int i = 0; i < validation.getRegions().countRanges(); i++) {
                int column = validation.getRegions().getCellRangeAddress(i).getFirstColumn();
                if (column >= 0 && column < headers.size()) {
                    byColumn.put(headers.get(column), formula);
                }
            }
        }
        return byColumn;
    }

    /** Resolves a defined name to the values sitting in the range it points at. */
    private List<String> valuesOfNamedRange(XSSFWorkbook workbook, String name) {
        Name definedName = workbook.getName(name);
        assertThat(definedName).as("defined name %s", name).isNotNull();
        org.apache.poi.ss.util.AreaReference area =
                new org.apache.poi.ss.util.AreaReference(definedName.getRefersToFormula(), workbook.getSpreadsheetVersion());
        Sheet sheet = workbook.getSheet(area.getFirstCell().getSheetName());
        List<String> values = new ArrayList<>();
        for (org.apache.poi.ss.util.CellReference reference : area.getAllReferencedCells()) {
            Row row = sheet.getRow(reference.getRow());
            Cell cell = row == null ? null : row.getCell(reference.getCol());
            if (cell != null) {
                values.add(cell.getStringCellValue());
            }
        }
        return values;
    }

    private String formatOfColumn(XSSFSheet sheet, int columnIndex) {
        return sheet.getColumnStyle(columnIndex).getDataFormatString();
    }

    /** Writes data rows into a generated template, the way a user filling it in would. */
    private byte[] fillIn(byte[] template, List<Map<String, String>> rows) {
        try (XSSFWorkbook workbook = open(template)) {
            Sheet sheet = workbook.getSheetAt(0);
            List<String> headers = headersOf(template);
            int rowIndex = sheet.getLastRowNum() + 1;
            for (Map<String, String> values : rows) {
                Row row = sheet.createRow(rowIndex++);
                for (Map.Entry<String, String> entry : values.entrySet()) {
                    int column = headers.indexOf(entry.getKey());
                    assertThat(column).as("column %s exists in the template", entry.getKey()).isNotNegative();
                    row.createCell(column).setCellValue(entry.getValue());
                }
            }
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            workbook.write(out);
            return out.toByteArray();
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    private XSSFWorkbook open(byte[] file) {
        try {
            return new XSSFWorkbook(new ByteArrayInputStream(file));
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }
}
