package com.procurepal_services.stock_bridge_api.product.bulk;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.assertj.core.api.Assertions.catchThrowableOfType;

import com.procurepal_services.stock_bridge_api.entity.Product;
import com.procurepal_services.stock_bridge_api.imports.io.ImportLimits;
import com.procurepal_services.stock_bridge_api.imports.io.LookupSheetWriter;
import com.procurepal_services.stock_bridge_api.imports.io.SheetTable;
import com.procurepal_services.stock_bridge_api.imports.io.SpreadsheetReader;
import com.procurepal_services.stock_bridge_api.imports.io.TemplateConventions;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.stream.IntStream;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Name;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.xssf.usermodel.XSSFDataValidation;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.junit.jupiter.api.Test;
import org.springframework.mock.web.MockMultipartFile;

/**
 * The product template and its parser, tested against each other and against the written file
 * itself. No Spring: {@link ProductExcelService} takes one collaborator, and constructing it
 * directly keeps these fast enough to run on every save.
 *
 * <h2>Why several of these read the generated bytes back with POI</h2>
 * A data validation that silently failed to attach is invisible to a test that checks cell values -
 * the file opens, the columns are right, the examples are there, and the dropdown the whole feature
 * was for simply is not. It is the classic failure of generating spreadsheets, and the only way to
 * catch it is to read the validation records out of the written file and assert on them, which is
 * what {@link #everyIntendedColumnReallyHasADropdownInTheWrittenFile} does.
 */
class ProductExcelServiceTest {

    private final ProductExcelService service = new ProductExcelService(new SpreadsheetReader());

    private static final List<String> VENDORS =
            List.of("Dangote Nigeria Plc", "Ade Foods Ltd", "Olam Agri Nigeria");

    // ------------------------------------------------------------------------ the product sheet ----
    // BULK_IMPORT_CX_PLAN.md task 1.6: a help tab first, headers named for people, a guidance row,
    // a note and worked examples, dropdowns, optional starting stock and price, a category.

    private static final ProductTemplateContext COMPANY =
            new ProductTemplateContext(false, VENDORS, false, List.of("Drinks", "Grains"));

    @Test
    void theSellerTemplateCarriesEveryColumnInOrderInPlainWords() {
        assertThat(headersOf(service.generateTemplate(new ProductTemplateContext(true, VENDORS, false, List.of()))))
                .containsExactly("Product name *", "Your code *", "Comes in", "Size of one", "Supplier",
                        "How many you have now", "Price you pay for one (₦)", "Selling price (₦) *",
                        "Warn me when I have", "Category", "Notes", "Supplier's code for it");
    }

    @Test
    void aCompanyTemplateHasNoSellingPriceAndAGeneratedCodeCompanyHasNoCodeColumn() {
        assertThat(headersOf(service.generateTemplate(COMPANY)))
                .doesNotContain("Selling price (₦) *")
                .contains("Your code *", "How many you have now", "Price you pay for one (₦)", "Category");
        assertThat(headersOf(service.generateTemplate(new ProductTemplateContext(false, VENDORS, true, List.of()))))
                .doesNotContain("Your code *");
    }

    @Test
    void theMainSupplierColumnIsGone() {
        assertThat(headersOf(service.generateTemplate(COMPANY)))
                .noneMatch(header -> header.toLowerCase().contains("preferred") || header.toLowerCase().contains("main"));
    }

    @Test
    void theHelpTabOpensFirstAndTheDataTabIsFrozenUnderItsGuidanceRow() {
        try (XSSFWorkbook workbook = open(service.generateTemplate(COMPANY))) {
            assertThat(workbook.getSheetName(0)).isEqualTo(TemplateConventions.HELP_SHEET_NAME);
            assertThat(workbook.getActiveSheetIndex()).isZero();
            Sheet data = workbook.getSheet("Products");
            assertThat(data.getPaneInformation().getHorizontalSplitPosition()).isEqualTo((short) 2);
            assertThat(data.getRow(1).getCell(0).getStringCellValue()).startsWith(TemplateConventions.GUIDANCE_MARKER);
            assertThat(data.getRow(0).getCell(0).getCellComment()).as("no hover-only instructions").isNull();
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    /**
     * The examples are ordinary rows under a note. Read back, the guidance and the note are
     * dropped, and each example - left as shipped - is recognised as one.
     */
    @Test
    void theExamplesReadBackAsExamplesUntilSomeoneChangesThem() {
        byte[] template = service.generateTemplate(COMPANY);
        SheetTable table = new SpreadsheetReader().read(template, "products.xlsx");
        assertThat(table.rows()).hasSize(ProductExcelService.EXAMPLE_ROWS.size());
        assertThat(table.rows()).allSatisfy(row -> assertThat(ProductExcelService.isShippedExample(byField(table, row))).isTrue());

        Map<String, String> edited = new java.util.LinkedHashMap<>(byField(table, table.rows().get(0)));
        edited.put("opening_stock", "13");
        assertThat(ProductExcelService.isShippedExample(edited)).isFalse();

        Map<String, String> renamed = new java.util.LinkedHashMap<>(byField(table, table.rows().get(0)));
        renamed.put("name", "Rice (Royal Stallion)");
        assertThat(ProductExcelService.isShippedExample(renamed)).isFalse();
    }

    @Test
    void theDropdownsPointAtWhatItComesInTheSuppliersAndTheCategories() {
        byte[] template = service.generateTemplate(COMPANY);
        try (XSSFWorkbook workbook = open(template)) {
            XSSFSheet sheet = workbook.getSheet("Products");
            Map<String, String> ranges = dropdownRangesByColumn(sheet, headersOf(template));
            assertThat(ranges).containsOnlyKeys("Comes in", "Supplier", "Category");
            assertThat(valuesOfNamedRange(workbook, ranges.get("Supplier"))).containsExactlyElementsOf(VENDORS);
            assertThat(valuesOfNamedRange(workbook, ranges.get("Category"))).containsExactly("Drinks", "Grains");
            assertThat(valuesOfNamedRange(workbook, ranges.get("Comes in"))).contains("Bag", "Carton", "Keg", "Bottle");
            assertThat(workbook.isSheetHidden(workbook.getSheetIndex(LookupSheetWriter.SHEET_NAME))).isTrue();
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    @Test
    void aSupplierListPastTheCapLeavesTheColumnAsFreeText() {
        List<String> many = IntStream.range(0, ImportLimits.VENDOR_DROPDOWN_CAP + 1).mapToObj(i -> "Vendor " + i).toList();
        byte[] template = service.generateTemplate(new ProductTemplateContext(false, many, false, List.of()));
        try (XSSFWorkbook workbook = open(template)) {
            assertThat(dropdownRangesByColumn(workbook.getSheet("Products"), headersOf(template)))
                    .doesNotContainKeys("Supplier", "Category");
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    @Test
    void priceAndQuantityColumnsCarryNumberFormats() {
        byte[] template = service.generateTemplate(new ProductTemplateContext(true, VENDORS, false, List.of()));
        List<String> headers = headersOf(template);
        try (XSSFWorkbook workbook = open(template)) {
            XSSFSheet sheet = workbook.getSheet("Products");
            assertThat(formatOfColumn(sheet, headers.indexOf("Price you pay for one (₦)"))).isEqualTo("#,##0.00");
            assertThat(formatOfColumn(sheet, headers.indexOf("Selling price (₦) *"))).isEqualTo("#,##0.00");
            assertThat(formatOfColumn(sheet, headers.indexOf("How many you have now"))).isEqualTo("#,##0.###");
            assertThat(formatOfColumn(sheet, headers.indexOf("Warn me when I have"))).isEqualTo("#,##0.###");
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    private static Map<String, String> byField(SheetTable table, com.procurepal_services.stock_bridge_api.imports.io.SheetRow row) {
        Map<String, String> reverse = new java.util.HashMap<>();
        ProductExcelService.SHEET_HEADERS.forEach((field, header) -> reverse.put(header, field));
        Map<String, String> values = new java.util.LinkedHashMap<>();
        for (int i = 0; i < table.headers().size(); i++) {
            String field = reverse.get(table.headers().get(i));
            if (field != null) {
                String value = row.cell(i);
                values.put(field, value == null ? "" : value);
            }
        }
        return values;
    }

    // ------------------------------------------ the rename, and the promise that survived it ----

    /**
     * UNIT_UX_CONTRACT.md section 7, non-negotiable 8. A tenant fills in the template they saved a
     * year ago and uploads it: {@code quantity_on_hand} still means what it always meant, with no
     * new errors and nothing for them to fix.
     *
     * <p>This is the assertion that makes the rename affordable. Without it the honest options were
     * to keep a column name that had already caused a 50x data error (P0-3) or to break every saved
     * copy in the field.
     */
    @Test
    void aTemplateSavedBeforeTheRenameStillParsesThroughTheAlias() {
        List<ParsedProductRow> rows = service.parse(multipart("old-products.csv", csv(
                "name,sku,description,cost_price,quantity_on_hand,low_stock_threshold,unit_of_measure,"
                        + "packaging_unit,packaging_size,vendor_name,vendor_sku,is_preferred_vendor\n"
                        + "Rice 50kg,RICE-50,,900,20,2,KG,BAG,50,Dangote Nigeria Plc,DN-1,TRUE\n")), false);

        assertThat(rows).singleElement().satisfies(row -> {
            assertThat(row.costPrice()).isEqualByComparingTo("900");
            assertThat(row.unitOfMeasure()).isEqualTo("KG");
            assertThat(row.packagingUnit()).isEqualTo("BAG");
            // Every one of the five old headers resolved - all three unit columns came through,
            // which is only possible if unit_of_measure, packaging_unit and packaging_size each
            // mapped to their section 9.4 names.
            assertThat(row.packagingSize()).isEqualByComparingTo("50");
            // And the aliased quantity is read under section 9.1's rule, NOT its old meaning:
            // 20 beside a Bag of 50 kg is twenty bags. The contract is explicit that this is
            // intended - nothing has reached production, so there is no saved sheet whose bare
            // number needs its old meaning preserved.
            assertThat(row.quantityOnHand()).isEqualTo(1_000);
            assertThat(row.lowStockThreshold()).isEqualTo(100);
        });
    }

    /** An error on an old sheet names the header that file actually uses, not the one we would write. */
    @Test
    void anErrorOnAnOldSheetNamesTheHeaderThatFileUses() {
        BulkUploadValidationException thrown = catchThrowableOfType(
                BulkUploadValidationException.class,
                () -> service.parse(multipart("old-products.csv", csv(
                        "name,sku,quantity_on_hand\nRice 50kg,RICE-50,minus twelve\n")), false));

        assertThat(thrown.getErrors()).singleElement()
                .satisfies(error -> assertThat(error.column()).isEqualTo("quantity_on_hand"));
    }

    /** And the new one names the new header, for a file downloaded today. */
    @Test
    void anErrorOnANewSheetNamesOpeningStock() {
        BulkUploadValidationException thrown = catchThrowableOfType(
                BulkUploadValidationException.class,
                () -> service.parse(multipart("products.csv", csv(
                        "name,sku,opening_stock\nRice 50kg,RICE-50,minus twelve\n")), false));

        assertThat(thrown.getErrors()).singleElement()
                .satisfies(error -> assertThat(error.column()).isEqualTo("opening_stock"));
    }

    /**
     * The export is the other half of "export, edit, upload back", so its unit columns carry the
     * same labels the template's dropdowns offer - contract section 7, non-negotiable 4. A cell
     * reading "KG" on one file and "Kilogram (kg)" on the other would be two vocabularies inside
     * one workflow.
     */
    @Test
    void theExportWritesUnitLabelsNotCodes() {
        Product rice = new Product();
        rice.setId(UUID.randomUUID());
        rice.setName("Rice 50kg");
        rice.setSku("RICE-50");
        rice.setUnitOfMeasure("KG");
        rice.setPackagingUnit("BAG");
        rice.setPackagingSize(new java.math.BigDecimal("50"));

        try (XSSFWorkbook workbook = open(service.exportProducts(List.of(rice)))) {
            List<String> headers = headersOf(service.exportProducts(List.of(rice)));
            Row row = workbook.getSheet("Products").getRow(2);
            // Section 15: one phrase, the same shape the user types back in.
            assertThat(row.getCell(headers.indexOf("Size of one")).getStringCellValue()).isEqualTo("50 kg");
            assertThat(row.getCell(headers.indexOf("Comes in")).getStringCellValue()).isEqualTo("Bag");
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    /**
     * {@code opening_stock_counted_in} is gone - UNIT_UX_CONTRACT.md section 9.1 - and not as a
     * deprecation: no column, no alias, no fallback reading.
     *
     * <p>It was itself a replacement for a cross-field WARNING ("12 kg - did you mean 12 bags?")
     * whose predicate guessed badly in both directions, and the reasoning that replaced it was
     * sound: a quantity whose unit is inferred from a neighbour is what section 1 forbids
     * everywhere else. What that reasoning missed is that the neighbour IS the declaration. "30
     * bags" states its unit in English; a row saying Keg, 50, 30 states it just as plainly. So
     * the column was asking a question the row had already answered two cells to its left.
     */
    @Test
    void theCountedInColumnIsGoneEntirelyAndItsOldSpellingIsNotAnAlias() {
        List<String> headers = headersOf(service.generateTemplate(new ProductTemplateContext(false, VENDORS, false)));
        assertThat(headers).doesNotContain("opening_stock_counted_in");

        // Not merely absent from the template - not readable either. A file still carrying the
        // column parses fine and the column is simply not one of ours.
        List<ParsedProductRow> rows = service.parse(multipart("products.csv", csv(
                "name,sku,pack,contains,opening_stock,opening_stock_counted_in\n"
                        + "Palm Oil,OIL-1,Keg,50 ml,30,Milliliter (ml)\n")), false);

        // 30 kegs - 1,500 ml. The stray column said "ml" and changed nothing, because the row
        // decides.
        assertThat(rows).singleElement()
                .satisfies(row -> assertThat(row.quantityOnHand()).isEqualTo(1_500));
    }

    /**
     * The headline case of section 9.1, on the sheet: thirty kegs of fifty millilitres commits as
     * <b>1,500 ml</b>.
     */
    @Test
    void aPackRowsOpeningStockCountsPacks() {
        List<ParsedProductRow> rows = service.parse(multipart("products.csv", csv(
                "name,sku,pack,contains,opening_stock,low_stock_alert_at\n"
                        + "Palm Oil,OIL-1,Keg,50 ml,30,5\n")), false);

        assertThat(rows).singleElement().satisfies(row -> {
            assertThat(row.quantityOnHand()).isEqualTo(1_500);
            // low_stock_alert_at follows the same rule - five kegs, 250 ml. Two quantity columns
            // on one row counting different things is the defect section 9 removes.
            assertThat(row.lowStockThreshold()).isEqualTo(250);
        });
    }

    /** And a row with no pack is its bare number, exactly as it always was. */
    @Test
    void aRowWithNoPackKeepsItsBareNumber() {
        List<ParsedProductRow> rows = service.parse(multipart("products.csv", csv(
                "name,sku,stock_unit,opening_stock,low_stock_alert_at\n"
                        + "Bolts,BOLT-1,Piece,600,50\n")), false);

        assertThat(rows).singleElement().satisfies(row -> {
            assertThat(row.quantityOnHand()).isEqualTo(600);
            assertThat(row.lowStockThreshold()).isEqualTo(50);
        });
    }

    /**
     * Thirty kegs and a half-full one is a real shelf, and an integer count of packs cannot say
     * it - section 9.1. Converted, then rounded HALF_UP at scale 0 like every other quantity.
     */
    @Test
    void aFractionalPackCountIsAcceptedAndConverted() {
        List<ParsedProductRow> rows = service.parse(multipart("products.csv", csv(
                "name,sku,pack,contains,opening_stock\n"
                        + "Palm Oil,OIL-1,Keg,50 ml,30.5\n"
                        + "Rice,RICE-1,Bag,3 kg,2.5\n")), false);

        assertThat(rows).extracting(ParsedProductRow::quantityOnHand)
                // 30.5 x 50 = 1,525 exactly; 2.5 x 3 = 7.5, HALF_UP to 8.
                .containsExactly(1_525, 8);
    }

    /**
     * A conversion that rounds to nothing is refused, never silently stored as zero - contract
     * section 3.1. Recording "we have none" for stock somebody typed is the same class of defect
     * as recording the wrong number.
     */
    @Test
    void aQuantityThatRoundsToZeroIsRefusedRatherThanStored() {
        BulkUploadValidationException thrown = catchThrowableOfType(
                BulkUploadValidationException.class,
                () -> service.parse(multipart("products.csv", csv(
                        "name,sku,contains,opening_stock\nGold Dust,GOLD-1,kg,0.4\n")), false));

        assertThat(thrown.getErrors()).singleElement().satisfies(error -> {
            assertThat(error.column()).isEqualTo("opening_stock");
            assertThat(error.message()).contains("less than one whole kg");
        });
    }

    /**
     * The export writes both quantities in the terms the columns are READ in - packs when the
     * product has one. That is what keeps "export, edit, re-upload" from multiplying the catalog
     * by the pack size on every trip.
     *
     * <p>The previous answer to the same problem was to leave a second column blank. Stating the
     * number in the column's own unit is the same guarantee without the second column.
     */
    @Test
    void theExportWritesPacksSoARoundTripDoesNotMultiply() {
        Product rice = new Product();
        rice.setId(java.util.UUID.randomUUID());
        rice.setName("Rice 50kg");
        rice.setSku("RICE-50");
        rice.setUnitOfMeasure("KG");
        rice.setPackagingUnit("BAG");
        rice.setPackagingSize(new java.math.BigDecimal("50"));
        rice.setQuantityOnHand(1000);
        rice.setLowStockThreshold(100);

        byte[] bytes = service.exportProducts(List.of(rice));
        List<String> headers = headersOf(bytes);
        try (XSSFWorkbook workbook = open(bytes)) {
            Row row = workbook.getSheet("Products").getRow(2);
            assertThat(row.getCell(headers.indexOf("How many you have now")).getNumericCellValue()).isEqualTo(20d);
            assertThat(row.getCell(headers.indexOf("Warn me when I have")).getNumericCellValue()).isEqualTo(2d);
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    /** A product with no pack exports its stock-unit figure unchanged. */
    @Test
    void theExportOfALoosProductWritesStockUnitsUnchanged() {
        Product bolts = new Product();
        bolts.setId(java.util.UUID.randomUUID());
        bolts.setName("Bolts");
        bolts.setSku("BOLT-1");
        bolts.setUnitOfMeasure("PIECE");
        bolts.setQuantityOnHand(600);

        byte[] bytes = service.exportProducts(List.of(bolts));
        List<String> headers = headersOf(bytes);
        try (XSSFWorkbook workbook = open(bytes)) {
            assertThat(workbook.getSheet("Products").getRow(2).getCell(headers.indexOf("How many you have now")).getNumericCellValue())
                    .isEqualTo(600d);
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    // ---------------------------------------------------------------------- the legacy parser ----
    // The old /api/products/bulk-upload parser still reads the older headers below; the product
    // sheet itself is read by the import page (BulkImportRoundTripIntegrationTest).

    /** The same content as a CSV must parse to the same rows - the format is the user's choice, not ours. */
    @Test
    void aCsvOfTheSameContentParsesToTheSameRows() {
        byte[] csv = ("name,sku,cost_price,quantity_on_hand,unit_of_measure,packaging_unit,packaging_size,"
                        + "vendor_name,vendor_sku,is_preferred_vendor\n"
                        + "Rice 50kg,RICE-50,42000,40,KG,BAG,50,Dangote Nigeria Plc,DN-RICE-50,TRUE\n")
                .getBytes(StandardCharsets.UTF_8);

        List<ParsedProductRow> rows = service.parse(multipart("products.csv", csv), false);

        assertThat(rows).hasSize(1);
        assertThat(rows.get(0).sku()).isEqualTo("RICE-50");
        assertThat(rows.get(0).unitOfMeasure()).isEqualTo("KG");
        assertThat(rows.get(0).packagingUnit()).isEqualTo("BAG");
        assertThat(rows.get(0).vendorName()).isEqualTo("Dangote Nigeria Plc");
        assertThat(rows.get(0).preferredVendor()).isTrue();
    }

    // ------------------------------------------------------------------- forgiveness on parse ----

    /**
     * The point of the whole alias table, seen from the outside: a file typed rather than picked
     * still imports, and produces the normalized CODE rather than whatever the user wrote.
     */
    @Test
    void typedUnitSpellingsAreAcceptedAndNormalizedToCodes() {
        List<ParsedProductRow> rows = service.parse(multipart("products.csv", csv(
                "name,sku,unit_of_measure,packaging_unit,packaging_size\n"
                        + "Rice 50kg,RICE-50,kilogram,bags,50\n"
                        + "Palm Oil,OIL-25,litres,jerrycan,25\n")), false);

        assertThat(rows).extracting(ParsedProductRow::unitOfMeasure).containsExactly("KG", "LITER");
        assertThat(rows).extracting(ParsedProductRow::packagingUnit).containsExactly("BAG", "KEG");
    }

    /** And the money people actually type - the comma is a thousands separator here, not a typo. */
    @Test
    void formattedMoneyAndQuantitiesAreUnderstood() {
        List<ParsedProductRow> rows = service.parse(multipart("products.csv", csv(
                "name,sku,cost_price,opening_stock\nRice 50kg,RICE-50,\"N45,000.00\",\"1,200\"\n")), false);

        assertThat(rows.get(0).costPrice()).isEqualByComparingTo("45000.00");
        assertThat(rows.get(0).quantityOnHand()).isEqualTo(1200);
    }

    /**
     * A code from the wrong half of the catalog is still rejected - the role split is what removes
     * the "50kg bag" ambiguity - but the message now names the column it does belong in, instead of
     * claiming we do not recognise a value we plainly do.
     */
    @Test
    void aPackagingCodeInTheBaseUnitColumnIsRejectedWithAHintNamingTheRightColumn() {
        BulkUploadValidationException thrown = catchThrowableOfType(
                BulkUploadValidationException.class,
                () -> service.parse(multipart("products.csv", csv(
                        "name,sku,unit_of_measure\nRice 50kg,RICE-50,BAG\n")), false));

        assertThat(thrown.getErrors()).singleElement().satisfies(error -> {
            assertThat(error.row()).isEqualTo(2);
            // The header the FILE used, since this fixture is an old-spelling sheet.
            assertThat(error.column()).isEqualTo("unit_of_measure");
            assertThat(error.message()).contains("BAG").contains("not a recognized stock unit");
            // The hint names the column as the sheet spells it TODAY - pointing somebody at a
            // "packaging_unit" column their template no longer has is an instruction they cannot
            // follow.
            assertThat(error.message()).contains("pack");
        });
    }

    /** A vendor SKU with no vendor named is not a partly-filled row; it is a row we cannot interpret. */
    @Test
    void vendorSkuAndPreferredFlagRequireAVendorName() {
        BulkUploadValidationException thrown = catchThrowableOfType(
                BulkUploadValidationException.class,
                () -> service.parse(multipart("products.csv", csv(
                        "name,sku,vendor_sku,is_preferred_vendor\nRice 50kg,RICE-50,DN-1,TRUE\n")), false));

        assertThat(thrown.getErrors()).extracting(ProductRowError::column)
                .containsExactlyInAnyOrder("vendor_sku", "is_preferred_vendor");
    }

    /** TRUE is what the dropdown offers; everything a person would write instead means the same thing. */
    @Test
    void thePreferredFlagAcceptsEveryReasonableSpellingOfYes() {
        List<ParsedProductRow> rows = service.parse(multipart("products.csv", csv(
                "name,sku,vendor_name,is_preferred_vendor\n"
                        + "A,SKU-1,Dangote Nigeria Plc,TRUE\n"
                        + "B,SKU-2,Dangote Nigeria Plc,yes\n"
                        + "C,SKU-3,Dangote Nigeria Plc,Y\n"
                        + "D,SKU-4,Dangote Nigeria Plc,1\n"
                        + "E,SKU-5,Dangote Nigeria Plc,\n"
                        + "F,SKU-6,Dangote Nigeria Plc,no\n")), false);

        assertThat(rows).extracting(ParsedProductRow::preferredVendor)
                .containsExactly(true, true, true, true, false, false);
    }

    // ----------------------------------------------------------------- limits and file errors ----

    /**
     * The over-cap rejection reaches the caller as a file-level row-0 error carrying the real
     * number, not as a parse failure and not after a full parse.
     */
    @Test
    void anOverCapFileIsRejectedWithTheRealRowCountBeforeAnyRowIsValidated() {
        StringBuilder content = new StringBuilder("name,sku,unit_of_measure\n");
        for (int i = 0; i < 5100; i++) {
            // Every row also carries an invalid unit. If the cap were enforced after parsing,
            // these would come back as 5,100 row errors instead of one file error.
            content.append("Product ").append(i).append(",SKU-").append(i).append(",NOT-A-UNIT\n");
        }

        BulkUploadValidationException thrown = catchThrowableOfType(
                BulkUploadValidationException.class,
                () -> service.parse(multipart("products.csv", csv(content.toString())), false));

        assertThat(thrown.getErrors()).singleElement().satisfies(error -> {
            assertThat(error.row()).isZero();
            assertThat(error.column()).isEqualTo("file");
            assertThat(error.message()).contains("5,100 rows").contains("the limit is 5,000");
        });
    }

    @Test
    void garbageStillSaysTheFileIsNotAValidXlsx() {
        assertThatThrownBy(() -> service.parse(multipart("products.xlsx", csv("nonsense")), false))
                .isInstanceOf(BulkUploadValidationException.class)
                .satisfies(e -> assertThat(((BulkUploadValidationException) e).getErrors())
                        .singleElement()
                        .satisfies(error -> assertThat(error.message())
                                .isEqualTo("The uploaded file is not a valid .xlsx file")));
    }

    // ------------------------------------------------------------------------------ fixtures ----

    private MockMultipartFile multipart(String filename, byte[] content) {
        return new MockMultipartFile("file", filename, "application/octet-stream", content);
    }

    private byte[] csv(String content) {
        return content.getBytes(StandardCharsets.UTF_8);
    }

    private List<String> headersOf(byte[] file) {
        try (XSSFWorkbook workbook = open(file)) {
            List<String> headers = new ArrayList<>();
            Sheet data = workbook.getSheet("Products");
            for (Cell cell : (data == null ? workbook.getSheetAt(0) : data).getRow(0)) {
                headers.add(cell.getStringCellValue());
            }
            return headers;
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    /** Reads the validation records back out and maps each covered column to the range it points at. */
    private Map<String, String> dropdownRangesByColumn(XSSFSheet sheet, List<String> headers) {
        Map<String, String> byColumn = new java.util.LinkedHashMap<>();
        for (XSSFDataValidation validation : sheet.getDataValidations()) {
            String formula = validation.getValidationConstraint().getFormula1();
            for (int i = 0; i < validation.getRegions().countRanges(); i++) {
                int column = validation.getRegions().getCellRangeAddress(i).getFirstColumn();
                if (column >= 0 && column < headers.size()) {
                    byColumn.put(headers.get(column), formula);
                }
            }
        }
        return byColumn;
    }

    /** Resolves a defined name to the values sitting in the range it points at. */
    private List<String> valuesOfNamedRange(XSSFWorkbook workbook, String name) {
        Name definedName = workbook.getName(name);
        assertThat(definedName).as("defined name %s", name).isNotNull();
        org.apache.poi.ss.util.AreaReference area =
                new org.apache.poi.ss.util.AreaReference(definedName.getRefersToFormula(), workbook.getSpreadsheetVersion());
        Sheet sheet = workbook.getSheet(area.getFirstCell().getSheetName());
        List<String> values = new ArrayList<>();
        for (org.apache.poi.ss.util.CellReference reference : area.getAllReferencedCells()) {
            Row row = sheet.getRow(reference.getRow());
            Cell cell = row == null ? null : row.getCell(reference.getCol());
            if (cell != null) {
                values.add(cell.getStringCellValue());
            }
        }
        return values;
    }

    private String formatOfColumn(XSSFSheet sheet, int columnIndex) {
        return sheet.getColumnStyle(columnIndex).getDataFormatString();
    }

    private XSSFWorkbook open(byte[] file) {
        try {
            return new XSSFWorkbook(new ByteArrayInputStream(file));
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }
}
