package com.procurepal_services.stock_bridge_api.product.bulk;

import static org.assertj.core.api.Assertions.assertThat;

import com.procurepal_services.stock_bridge_api.entity.Product;
import com.procurepal_services.stock_bridge_api.imports.io.ImportLimits;
import com.procurepal_services.stock_bridge_api.imports.io.LookupSheetWriter;
import com.procurepal_services.stock_bridge_api.imports.io.SheetTable;
import com.procurepal_services.stock_bridge_api.imports.io.SpreadsheetReader;
import com.procurepal_services.stock_bridge_api.imports.io.TemplateConventions;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.stream.IntStream;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Name;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.xssf.usermodel.XSSFDataValidation;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.junit.jupiter.api.Test;

/**
 * The product template and export, tested against the written file itself. No Spring:
 * {@link ProductExcelService} has no collaborators, and constructing it directly keeps these fast
 * enough to run on every save. Reading a product sheet back is the import engine's job
 * (BulkImportRoundTripIntegrationTest).
 *
 * <h2>Why several of these read the generated bytes back with POI</h2>
 * A data validation that silently failed to attach is invisible to a test that checks cell values -
 * the file opens, the columns are right, the examples are there, and the dropdown the whole feature
 * was for simply is not. It is the classic failure of generating spreadsheets, and the only way to
 * catch it is to read the validation records out of the written file and assert on them, which is
 * what {@link #everyIntendedColumnReallyHasADropdownInTheWrittenFile} does.
 */
class ProductExcelServiceTest {

    private final ProductExcelService service = new ProductExcelService();

    private static final List<String> VENDORS =
            List.of("Dangote Nigeria Plc", "Ade Foods Ltd", "Olam Agri Nigeria");

    // ------------------------------------------------------------------------ the product sheet ----
    // BULK_IMPORT_CX_PLAN.md task 1.6: a help tab first, headers named for people, a guidance row,
    // a note and worked examples, dropdowns, optional starting stock and price, a category.

    private static final ProductTemplateContext COMPANY =
            new ProductTemplateContext(false, VENDORS, false, List.of("Drinks", "Grains"));

    @Test
    void theSellerTemplateCarriesEveryColumnInOrderInPlainWords() {
        assertThat(headersOf(service.generateTemplate(new ProductTemplateContext(true, VENDORS, false, List.of()))))
                .containsExactly("Product name *", "Your code *", "Comes in", "Size of one", "Supplier",
                        "How many you have now", "Price you pay for one (₦)", "Selling price (₦) *",
                        "Warn me when I have", "Category", "Notes", "Supplier's code for it", "Barcode");
    }

    @Test
    void aCompanyTemplateHasNoSellingPriceAndAGeneratedCodeCompanyHasNoCodeColumn() {
        assertThat(headersOf(service.generateTemplate(COMPANY)))
                .doesNotContain("Selling price (₦) *")
                .contains("Your code *", "How many you have now", "Price you pay for one (₦)", "Category");
        assertThat(headersOf(service.generateTemplate(new ProductTemplateContext(false, VENDORS, true, List.of()))))
                .doesNotContain("Your code *");
    }

    @Test
    void theMainSupplierColumnIsGone() {
        assertThat(headersOf(service.generateTemplate(COMPANY)))
                .noneMatch(header -> header.toLowerCase().contains("preferred") || header.toLowerCase().contains("main"));
    }

    @Test
    void theHelpTabOpensFirstAndTheDataTabIsFrozenUnderItsGuidanceRow() {
        try (XSSFWorkbook workbook = open(service.generateTemplate(COMPANY))) {
            assertThat(workbook.getSheetName(0)).isEqualTo(TemplateConventions.HELP_SHEET_NAME);
            assertThat(workbook.getActiveSheetIndex()).isZero();
            Sheet data = workbook.getSheet("Products");
            assertThat(data.getPaneInformation().getHorizontalSplitPosition()).isEqualTo((short) 2);
            assertThat(data.getRow(1).getCell(0).getStringCellValue()).startsWith(TemplateConventions.GUIDANCE_MARKER);
            assertThat(data.getRow(0).getCell(0).getCellComment()).as("no hover-only instructions").isNull();
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    /**
     * The examples are ordinary rows under a note. Read back, the guidance and the note are
     * dropped, and each example - left as shipped - is recognised as one.
     */
    @Test
    void theExamplesReadBackAsExamplesUntilSomeoneChangesThem() {
        byte[] template = service.generateTemplate(COMPANY);
        SheetTable table = new SpreadsheetReader().read(template, "products.xlsx");
        assertThat(table.rows()).hasSize(ProductExcelService.EXAMPLE_ROWS.size());
        assertThat(table.rows()).allSatisfy(row -> assertThat(ProductExcelService.isShippedExample(byField(table, row))).isTrue());

        Map<String, String> edited = new java.util.LinkedHashMap<>(byField(table, table.rows().get(0)));
        edited.put("opening_stock", "13");
        assertThat(ProductExcelService.isShippedExample(edited)).isFalse();

        Map<String, String> renamed = new java.util.LinkedHashMap<>(byField(table, table.rows().get(0)));
        renamed.put("name", "Rice (Royal Stallion)");
        assertThat(ProductExcelService.isShippedExample(renamed)).isFalse();
    }

    @Test
    void theDropdownsPointAtWhatItComesInTheSuppliersAndTheCategories() {
        byte[] template = service.generateTemplate(COMPANY);
        try (XSSFWorkbook workbook = open(template)) {
            XSSFSheet sheet = workbook.getSheet("Products");
            Map<String, String> ranges = dropdownRangesByColumn(sheet, headersOf(template));
            assertThat(ranges).containsOnlyKeys("Comes in", "Supplier", "Category");
            assertThat(valuesOfNamedRange(workbook, ranges.get("Supplier"))).containsExactlyElementsOf(VENDORS);
            assertThat(valuesOfNamedRange(workbook, ranges.get("Category"))).containsExactly("Drinks", "Grains");
            assertThat(valuesOfNamedRange(workbook, ranges.get("Comes in"))).contains("Bag", "Carton", "Keg", "Bottle");
            assertThat(workbook.isSheetHidden(workbook.getSheetIndex(LookupSheetWriter.SHEET_NAME))).isTrue();
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    @Test
    void aSupplierListPastTheCapLeavesTheColumnAsFreeText() {
        List<String> many = IntStream.range(0, ImportLimits.VENDOR_DROPDOWN_CAP + 1).mapToObj(i -> "Vendor " + i).toList();
        byte[] template = service.generateTemplate(new ProductTemplateContext(false, many, false, List.of()));
        try (XSSFWorkbook workbook = open(template)) {
            assertThat(dropdownRangesByColumn(workbook.getSheet("Products"), headersOf(template)))
                    .doesNotContainKeys("Supplier", "Category");
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    @Test
    void priceAndQuantityColumnsCarryNumberFormats() {
        byte[] template = service.generateTemplate(new ProductTemplateContext(true, VENDORS, false, List.of()));
        List<String> headers = headersOf(template);
        try (XSSFWorkbook workbook = open(template)) {
            XSSFSheet sheet = workbook.getSheet("Products");
            assertThat(formatOfColumn(sheet, headers.indexOf("Price you pay for one (₦)"))).isEqualTo("#,##0.00");
            assertThat(formatOfColumn(sheet, headers.indexOf("Selling price (₦) *"))).isEqualTo("#,##0.00");
            assertThat(formatOfColumn(sheet, headers.indexOf("How many you have now"))).isEqualTo("#,##0.###");
            assertThat(formatOfColumn(sheet, headers.indexOf("Warn me when I have"))).isEqualTo("#,##0.###");
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    private static Map<String, String> byField(SheetTable table, com.procurepal_services.stock_bridge_api.imports.io.SheetRow row) {
        Map<String, String> reverse = new java.util.HashMap<>();
        ProductExcelService.SHEET_HEADERS.forEach((field, header) -> reverse.put(header, field));
        Map<String, String> values = new java.util.LinkedHashMap<>();
        for (int i = 0; i < table.headers().size(); i++) {
            String field = reverse.get(table.headers().get(i));
            if (field != null) {
                String value = row.cell(i);
                values.put(field, value == null ? "" : value);
            }
        }
        return values;
    }

    /**
     * The export is the other half of "export, edit, upload back", so its unit columns carry the
     * same labels the template's dropdowns offer - contract section 7, non-negotiable 4. A cell
     * reading "KG" on one file and "Kilogram (kg)" on the other would be two vocabularies inside
     * one workflow.
     */
    @Test
    void theExportWritesUnitLabelsNotCodes() {
        Product rice = new Product();
        rice.setId(UUID.randomUUID());
        rice.setName("Rice 50kg");
        rice.setSku("RICE-50");
        rice.setUnitOfMeasure("KG");
        rice.setPackagingUnit("BAG");
        rice.setPackagingSize(new java.math.BigDecimal("50"));

        try (XSSFWorkbook workbook = open(service.exportProducts(List.of(rice)))) {
            List<String> headers = headersOf(service.exportProducts(List.of(rice)));
            Row row = workbook.getSheet("Products").getRow(2);
            // Section 15: one phrase, the same shape the user types back in.
            assertThat(row.getCell(headers.indexOf("Size of one")).getStringCellValue()).isEqualTo("50 kg");
            assertThat(row.getCell(headers.indexOf("Comes in")).getStringCellValue()).isEqualTo("Bag");
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    /**
     * {@code opening_stock_counted_in} is gone - UNIT_UX_CONTRACT.md section 9.1 - and not as a
     * deprecation: no column, no alias, no fallback reading.
     *
     * <p>It was itself a replacement for a cross-field WARNING ("12 kg - did you mean 12 bags?")
     * whose predicate guessed badly in both directions, and the reasoning that replaced it was
     * sound: a quantity whose unit is inferred from a neighbour is what section 1 forbids
     * everywhere else. What that reasoning missed is that the neighbour IS the declaration. "30
     * bags" states its unit in English; a row saying Keg, 50, 30 states it just as plainly. So
     * the column was asking a question the row had already answered two cells to its left.
     */
    @Test
    void theCountedInColumnIsGoneFromTheTemplate() {
        List<String> headers = headersOf(service.generateTemplate(new ProductTemplateContext(false, VENDORS, false)));
        assertThat(headers).doesNotContain("opening_stock_counted_in");
    }

    /**
     * The export writes both quantities in the terms the columns are READ in - packs when the
     * product has one. That is what keeps "export, edit, re-upload" from multiplying the catalog
     * by the pack size on every trip.
     *
     * <p>The previous answer to the same problem was to leave a second column blank. Stating the
     * number in the column's own unit is the same guarantee without the second column.
     */
    @Test
    void theExportWritesPacksSoARoundTripDoesNotMultiply() {
        Product rice = new Product();
        rice.setId(java.util.UUID.randomUUID());
        rice.setName("Rice 50kg");
        rice.setSku("RICE-50");
        rice.setUnitOfMeasure("KG");
        rice.setPackagingUnit("BAG");
        rice.setPackagingSize(new java.math.BigDecimal("50"));
        rice.setQuantityOnHand(1000);
        rice.setLowStockThreshold(100);

        byte[] bytes = service.exportProducts(List.of(rice));
        List<String> headers = headersOf(bytes);
        try (XSSFWorkbook workbook = open(bytes)) {
            Row row = workbook.getSheet("Products").getRow(2);
            assertThat(row.getCell(headers.indexOf("How many you have now")).getNumericCellValue()).isEqualTo(20d);
            assertThat(row.getCell(headers.indexOf("Warn me when I have")).getNumericCellValue()).isEqualTo(2d);
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    /** A product with no pack exports its stock-unit figure unchanged. */
    @Test
    void theExportOfALoosProductWritesStockUnitsUnchanged() {
        Product bolts = new Product();
        bolts.setId(java.util.UUID.randomUUID());
        bolts.setName("Bolts");
        bolts.setSku("BOLT-1");
        bolts.setUnitOfMeasure("PIECE");
        bolts.setQuantityOnHand(600);

        byte[] bytes = service.exportProducts(List.of(bolts));
        List<String> headers = headersOf(bytes);
        try (XSSFWorkbook workbook = open(bytes)) {
            assertThat(workbook.getSheet("Products").getRow(2).getCell(headers.indexOf("How many you have now")).getNumericCellValue())
                    .isEqualTo(600d);
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    // ------------------------------------------------------------------------------ fixtures ----

    private List<String> headersOf(byte[] file) {
        try (XSSFWorkbook workbook = open(file)) {
            List<String> headers = new ArrayList<>();
            Sheet data = workbook.getSheet("Products");
            for (Cell cell : (data == null ? workbook.getSheetAt(0) : data).getRow(0)) {
                headers.add(cell.getStringCellValue());
            }
            return headers;
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    /** Reads the validation records back out and maps each covered column to the range it points at. */
    private Map<String, String> dropdownRangesByColumn(XSSFSheet sheet, List<String> headers) {
        Map<String, String> byColumn = new java.util.LinkedHashMap<>();
        for (XSSFDataValidation validation : sheet.getDataValidations()) {
            String formula = validation.getValidationConstraint().getFormula1();
            for (int i = 0; i < validation.getRegions().countRanges(); i++) {
                int column = validation.getRegions().getCellRangeAddress(i).getFirstColumn();
                if (column >= 0 && column < headers.size()) {
                    byColumn.put(headers.get(column), formula);
                }
            }
        }
        return byColumn;
    }

    /** Resolves a defined name to the values sitting in the range it points at. */
    private List<String> valuesOfNamedRange(XSSFWorkbook workbook, String name) {
        Name definedName = workbook.getName(name);
        assertThat(definedName).as("defined name %s", name).isNotNull();
        org.apache.poi.ss.util.AreaReference area =
                new org.apache.poi.ss.util.AreaReference(definedName.getRefersToFormula(), workbook.getSpreadsheetVersion());
        Sheet sheet = workbook.getSheet(area.getFirstCell().getSheetName());
        List<String> values = new ArrayList<>();
        for (org.apache.poi.ss.util.CellReference reference : area.getAllReferencedCells()) {
            Row row = sheet.getRow(reference.getRow());
            Cell cell = row == null ? null : row.getCell(reference.getCol());
            if (cell != null) {
                values.add(cell.getStringCellValue());
            }
        }
        return values;
    }

    private String formatOfColumn(XSSFSheet sheet, int columnIndex) {
        return sheet.getColumnStyle(columnIndex).getDataFormatString();
    }

    private XSSFWorkbook open(byte[] file) {
        try {
            return new XSSFWorkbook(new ByteArrayInputStream(file));
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }
}
